[k10_base]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
board_build.partitions = partitions.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
monitor_speed = 115200

[env:unihiker]
extends = k10_base
build_flags =
    ${k10_base.build_flags}
    -DModel=None

[env:unihiker-init-cn]
extends = k10_base
build_flags =
    ${k10_base.build_flags}
    -DModel=CN

[env:unihiker-init-en]
extends = k10_base
build_flags =
    ${k10_base.build_flags}
    -DModel=EN
